import { CustomerRecord } from "../types";

export const DEMO_CUSTOMERS: CustomerRecord[] = [
  // ==================== VIP CUSTOMERS ====================
  {
    id: "CUST-1001",
    name: "Sourav Mahata",
    city: "Kolkata (Park Street)",
    phoneMasked: "+91 98301 •••••",
    segment: "VIP Customers",
    recencyDays: 4,
    lastPurchaseDate: "2026-03-27",
    orderFrequency: 9,
    totalMonetary: 68500,
    avgOrderValue: 7611,
    discountSensitivityPct: 4,
    favoriteProduct: "Baluchari Silk Saree",
    favoriteCategory: "Handloom Sarees",
    riskStatus: "Healthy",
    customerAction: "Invite to annual Private Handloom Conclave & offer complimentary artisan consultation."
  },
  {
    id: "CUST-1006",
    name: "Ananya Sen",
    city: "Kolkata (Ballygunge)",
    phoneMasked: "+91 98312 •••••",
    segment: "VIP Customers",
    recencyDays: 6,
    lastPurchaseDate: "2026-03-25",
    orderFrequency: 8,
    totalMonetary: 59200,
    avgOrderValue: 7400,
    discountSensitivityPct: 5,
    favoriteProduct: "Kashmiri Pashmina Shawl",
    favoriteCategory: "Luxury Winter",
    riskStatus: "Healthy",
    customerAction: "VIP priority concierge for bespoke bridal & ceremonial winter collections."
  },
  {
    id: "CUST-1011",
    name: "Vikramaditya Roy",
    city: "Mumbai (Bandra West)",
    phoneMasked: "+91 98205 •••••",
    segment: "VIP Customers",
    recencyDays: 8,
    lastPurchaseDate: "2026-03-23",
    orderFrequency: 11,
    totalMonetary: 92400,
    avgOrderValue: 8400,
    discountSensitivityPct: 3,
    favoriteProduct: "Dhakai Jamdani Saree",
    favoriteCategory: "Handloom Sarees",
    riskStatus: "Healthy",
    customerAction: "Offer customized wardrobe curation with master weaver certificates."
  },
  {
    id: "CUST-1015",
    name: "Dr. Malini Ganguly",
    city: "Kolkata (Salt Lake)",
    phoneMasked: "+91 98309 •••••",
    segment: "VIP Customers",
    recencyDays: 11,
    lastPurchaseDate: "2026-03-20",
    orderFrequency: 7,
    totalMonetary: 48900,
    avgOrderValue: 6985,
    discountSensitivityPct: 6,
    favoriteProduct: "Tussar Silk Kurti",
    favoriteCategory: "Ethnic Wear",
    riskStatus: "Healthy",
    customerAction: "Send premium festival gift box & early preview link for festive releases."
  },
  {
    id: "CUST-1020",
    name: "Rajiv Singhania",
    city: "New Delhi (South Ex)",
    phoneMasked: "+91 98114 •••••",
    segment: "VIP Customers",
    recencyDays: 9,
    lastPurchaseDate: "2026-03-22",
    orderFrequency: 6,
    totalMonetary: 44200,
    avgOrderValue: 7366,
    discountSensitivityPct: 2,
    favoriteProduct: "Silk Nehru Jacket",
    favoriteCategory: "Mens Ethnic",
    riskStatus: "Healthy",
    customerAction: "Provide VIP tailor home-measurement service & personalized embroidery."
  },
  {
    id: "CUST-1024",
    name: "Sunita Kothari",
    city: "Bengaluru (Indiranagar)",
    phoneMasked: "+91 98450 •••••",
    segment: "VIP Customers",
    recencyDays: 14,
    lastPurchaseDate: "2026-03-17",
    orderFrequency: 8,
    totalMonetary: 52600,
    avgOrderValue: 6575,
    discountSensitivityPct: 5,
    favoriteProduct: "Baluchari Silk Saree",
    favoriteCategory: "Handloom Sarees",
    riskStatus: "Healthy",
    customerAction: "Grant tier-1 loyalty points boost with lifetime exchange privileges."
  },

  // ==================== AT-RISK CUSTOMERS ====================
  {
    id: "CUST-1003",
    name: "Rajesh Bannerjee",
    city: "Kolkata (Alipore)",
    phoneMasked: "+91 98315 •••••",
    segment: "At-Risk Customers",
    recencyDays: 68,
    lastPurchaseDate: "2026-01-22",
    orderFrequency: 4,
    totalMonetary: 34800,
    avgOrderValue: 8700,
    discountSensitivityPct: 8,
    favoriteProduct: "Baluchari Silk Saree",
    favoriteCategory: "Handloom Sarees",
    riskStatus: "High Risk",
    customerAction: "CRITICAL: High historical spend dormant for 68 days. Trigger direct WhatsApp outreach with ₹2,000 revival credit."
  },
  {
    id: "CUST-1008",
    name: "Meera Dasgupta",
    city: "Kolkata (New Town)",
    phoneMasked: "+91 98302 •••••",
    segment: "At-Risk Customers",
    recencyDays: 74,
    lastPurchaseDate: "2026-01-16",
    orderFrequency: 3,
    totalMonetary: 24500,
    avgOrderValue: 8166,
    discountSensitivityPct: 7,
    favoriteProduct: "Tussar Silk Kurti",
    favoriteCategory: "Ethnic Wear",
    riskStatus: "High Risk",
    customerAction: "Past buyer of silk kurtis silent for 10+ weeks. Send targeted lookbook with seasonal revival perk."
  },
  {
    id: "CUST-1017",
    name: "Suman Ghosh",
    city: "Pune (Koregaon Park)",
    phoneMasked: "+91 98220 •••••",
    segment: "At-Risk Customers",
    recencyDays: 82,
    lastPurchaseDate: "2026-01-08",
    orderFrequency: 5,
    totalMonetary: 28400,
    avgOrderValue: 5680,
    discountSensitivityPct: 10,
    favoriteProduct: "Linen Casual Saree",
    favoriteCategory: "Casual Wear",
    riskStatus: "High Risk",
    customerAction: "Call directly from store manager offering concierge styling & no-cost home trial."
  },
  {
    id: "CUST-1026",
    name: "Aparna Mukherjee",
    city: "Kolkata (Gariahat)",
    phoneMasked: "+91 98363 •••••",
    segment: "At-Risk Customers",
    recencyDays: 61,
    lastPurchaseDate: "2026-01-29",
    orderFrequency: 4,
    totalMonetary: 21800,
    avgOrderValue: 5450,
    discountSensitivityPct: 9,
    favoriteProduct: "Kantha Stitch Stole",
    favoriteCategory: "Accessories",
    riskStatus: "High Risk",
    customerAction: "Reactivate via personalized SMS highlighting limited-stock Kantha arrivals."
  },
  {
    id: "CUST-1035",
    name: "Debashis Bose",
    city: "Hyderabad (Banjara Hills)",
    phoneMasked: "+91 98490 •••••",
    segment: "At-Risk Customers",
    recencyDays: 89,
    lastPurchaseDate: "2026-01-01",
    orderFrequency: 3,
    totalMonetary: 19200,
    avgOrderValue: 6400,
    discountSensitivityPct: 5,
    favoriteProduct: "Khadi Cotton Kurta",
    favoriteCategory: "Mens Ethnic",
    riskStatus: "High Risk",
    customerAction: "Send 'We Miss You' handwritten note with exclusive 25% discount voucher."
  },
  {
    id: "CUST-1044",
    name: "Nandita Sengupta",
    city: "Kolkata (Behala)",
    phoneMasked: "+91 98319 •••••",
    segment: "At-Risk Customers",
    recencyDays: 57,
    lastPurchaseDate: "2026-02-02",
    orderFrequency: 3,
    totalMonetary: 16700,
    avgOrderValue: 5566,
    discountSensitivityPct: 11,
    favoriteProduct: "Chanderi Dupatta",
    favoriteCategory: "Accessories",
    riskStatus: "Medium Risk",
    customerAction: "Trigger automatic re-engagement email campaign with bestseller recommendations."
  },

  // ==================== LOYAL CUSTOMERS ====================
  {
    id: "CUST-1002",
    name: "Priya Mukherjee",
    city: "Kolkata (Howrah)",
    phoneMasked: "+91 98304 •••••",
    segment: "Loyal Customers",
    recencyDays: 12,
    lastPurchaseDate: "2026-03-19",
    orderFrequency: 6,
    totalMonetary: 24800,
    avgOrderValue: 4133,
    discountSensitivityPct: 8,
    favoriteProduct: "Cotton Daily Saree",
    favoriteCategory: "Daily Wear",
    riskStatus: "Healthy",
    customerAction: "Reward with Tier-2 Loyalty status and 500 complimentary store points."
  },
  {
    id: "CUST-1007",
    name: "Amitabha Datta",
    city: "Kolkata (Jadavpur)",
    phoneMasked: "+91 98311 •••••",
    segment: "Loyal Customers",
    recencyDays: 15,
    lastPurchaseDate: "2026-03-16",
    orderFrequency: 5,
    totalMonetary: 19400,
    avgOrderValue: 3880,
    discountSensitivityPct: 6,
    favoriteProduct: "Khadi Cotton Kurta",
    favoriteCategory: "Mens Ethnic",
    riskStatus: "Healthy",
    customerAction: "Offer early-bird access to the upcoming Summer Khadi Festival."
  },
  {
    id: "CUST-1012",
    name: "Tanvi Parikh",
    city: "Ahmedabad (Navrangpura)",
    phoneMasked: "+91 98250 •••••",
    segment: "Loyal Customers",
    recencyDays: 18,
    lastPurchaseDate: "2026-03-13",
    orderFrequency: 7,
    totalMonetary: 27300,
    avgOrderValue: 3900,
    discountSensitivityPct: 7,
    favoriteProduct: "Zari Embroidered Blouse",
    favoriteCategory: "Ethnic Wear",
    riskStatus: "Healthy",
    customerAction: "Provide complimentary blouse tailoring customization on next order."
  },
  {
    id: "CUST-1018",
    name: "Subhash Chandra Roy",
    city: "Kolkata (Dum Dum)",
    phoneMasked: "+91 98307 •••••",
    segment: "Loyal Customers",
    recencyDays: 20,
    lastPurchaseDate: "2026-03-11",
    orderFrequency: 5,
    totalMonetary: 21500,
    avgOrderValue: 4300,
    discountSensitivityPct: 5,
    favoriteProduct: "Cotton Daily Saree",
    favoriteCategory: "Daily Wear",
    riskStatus: "Healthy",
    customerAction: "Recommend cross-sell accessories like Kantha stoles with purchase points."
  },
  {
    id: "CUST-1025",
    name: "Ritu Sharma",
    city: "Chandigarh (Sector 17)",
    phoneMasked: "+91 98150 •••••",
    segment: "Loyal Customers",
    recencyDays: 16,
    lastPurchaseDate: "2026-03-15",
    orderFrequency: 4,
    totalMonetary: 18600,
    avgOrderValue: 4650,
    discountSensitivityPct: 6,
    favoriteProduct: "Chanderi Dupatta",
    favoriteCategory: "Accessories",
    riskStatus: "Healthy",
    customerAction: "Send curated festive pairing suggestions tailored to past purchases."
  },

  // ==================== DISCOUNT SEEKERS ====================
  {
    id: "CUST-1005",
    name: "Pooja Chawla",
    city: "New Delhi (Lajpat Nagar)",
    phoneMasked: "+91 98101 •••••",
    segment: "Discount Seekers",
    recencyDays: 22,
    lastPurchaseDate: "2026-03-09",
    orderFrequency: 4,
    totalMonetary: 11200,
    avgOrderValue: 2800,
    discountSensitivityPct: 24,
    favoriteProduct: "Chanderi Dupatta",
    favoriteCategory: "Accessories",
    riskStatus: "Healthy",
    customerAction: "Target with Buy-2-Get-1 festive clearance bundle promotions."
  },
  {
    id: "CUST-1010",
    name: "Kavita Agarwal",
    city: "Kolkata (Burrabazar)",
    phoneMasked: "+91 98308 •••••",
    segment: "Discount Seekers",
    recencyDays: 19,
    lastPurchaseDate: "2026-03-12",
    orderFrequency: 3,
    totalMonetary: 9600,
    avgOrderValue: 3200,
    discountSensitivityPct: 28,
    favoriteProduct: "Kantha Stitch Stole",
    favoriteCategory: "Accessories",
    riskStatus: "Healthy",
    customerAction: "Send flash sale alerts during end-of-season inventory clearance."
  },
  {
    id: "CUST-1019",
    name: "Manish Verma",
    city: "Jaipur (MI Road)",
    phoneMasked: "+91 98290 •••••",
    segment: "Discount Seekers",
    recencyDays: 25,
    lastPurchaseDate: "2026-03-06",
    orderFrequency: 3,
    totalMonetary: 8400,
    avgOrderValue: 2800,
    discountSensitivityPct: 22,
    favoriteProduct: "Khadi Cotton Kurta",
    favoriteCategory: "Mens Ethnic",
    riskStatus: "Healthy",
    customerAction: "Incentivize bulk purchase with tiered discount thresholds (e.g. ₹500 off on ₹3,000)."
  },
  {
    id: "CUST-1028",
    name: "Shreya Ghoshal-Paul",
    city: "Kolkata (Tollygunge)",
    phoneMasked: "+91 98317 •••••",
    segment: "Discount Seekers",
    recencyDays: 21,
    lastPurchaseDate: "2026-03-10",
    orderFrequency: 4,
    totalMonetary: 12400,
    avgOrderValue: 3100,
    discountSensitivityPct: 26,
    favoriteProduct: "Organic Handspun Scarf",
    favoriteCategory: "Accessories",
    riskStatus: "Healthy",
    customerAction: "Market festival coupon code with limited 48-hour expiration."
  },

  // ==================== NEW CUSTOMERS ====================
  {
    id: "CUST-1004",
    name: "Arjun Chakraborty",
    city: "Kolkata (Kasba)",
    phoneMasked: "+91 98305 •••••",
    segment: "New Customers",
    recencyDays: 7,
    lastPurchaseDate: "2026-03-24",
    orderFrequency: 1,
    totalMonetary: 4200,
    avgOrderValue: 4200,
    discountSensitivityPct: 10,
    favoriteProduct: "Tussar Silk Kurti",
    favoriteCategory: "Ethnic Wear",
    riskStatus: "New",
    customerAction: "Send warm brand welcome onboarding pack & 15% discount on second order."
  },
  {
    id: "CUST-1009",
    name: "Deepika Rao",
    city: "Bengaluru (Koramangala)",
    phoneMasked: "+91 98455 •••••",
    segment: "New Customers",
    recencyDays: 9,
    lastPurchaseDate: "2026-03-22",
    orderFrequency: 1,
    totalMonetary: 6800,
    avgOrderValue: 6800,
    discountSensitivityPct: 5,
    favoriteProduct: "Organic Handspun Scarf",
    favoriteCategory: "Accessories",
    riskStatus: "New",
    customerAction: "Follow up with care guide for handspun garments to nurture repeat loyalty."
  },
  {
    id: "CUST-1014",
    name: "Rohan Bhattacharya",
    city: "Kolkata (Lake Gardens)",
    phoneMasked: "+91 98318 •••••",
    segment: "New Customers",
    recencyDays: 12,
    lastPurchaseDate: "2026-03-19",
    orderFrequency: 2,
    totalMonetary: 7600,
    avgOrderValue: 3800,
    discountSensitivityPct: 0,
    favoriteProduct: "Linen Casual Saree",
    favoriteCategory: "Casual Wear",
    riskStatus: "New",
    customerAction: "Invite to join Nexora Club membership with instant ₹500 welcome credit."
  },
  {
    id: "CUST-1022",
    name: "Bhavna Patel",
    city: "Surat (Adajan)",
    phoneMasked: "+91 98255 •••••",
    segment: "New Customers",
    recencyDays: 14,
    lastPurchaseDate: "2026-03-17",
    orderFrequency: 1,
    totalMonetary: 5400,
    avgOrderValue: 5400,
    discountSensitivityPct: 0,
    favoriteProduct: "Silk Nehru Jacket",
    favoriteCategory: "Mens Ethnic",
    riskStatus: "New",
    customerAction: "Send thank-you notification with cross-category ethnic recommendations."
  }
];
