import React, { useState } from "react";
import { ProductDecision } from "../types";
import { formatINR } from "../utils/currency";
import { Coins, ShieldCheck, PiggyBank, ArrowDownRight, ChevronDown, ChevronUp, AlertCircle } from "lucide-react";

interface BusinessImpactViewProps {
  decisions: ProductDecision[];
}

export const BusinessImpactView: React.FC<BusinessImpactViewProps> = ({ decisions }) => {
  const [showFormula, setShowFormula] = useState<boolean>(false);

  const totalRevenueProtected = decisions.reduce(
    (sum, d) => sum + d.financials.revenueProtected,
    0
  );
  const totalStockoutAvoided = decisions.reduce(
    (sum, d) => sum + d.financials.stockoutCostAvoided,
    0
  );
  const totalExcessFreed = decisions.reduce(
    (sum, d) => sum + d.financials.excessCapitalFreed,
    0
  );
  const totalHoldingSavings = Math.round(totalExcessFreed * (0.18 / 52));
  const totalPotentialSavings = totalStockoutAvoided + totalHoldingSavings;
  const estimatedBusinessImpact = totalRevenueProtected + totalPotentialSavings;

  return (
    <div className="space-y-8 max-w-7xl mx-auto">
      {/* Title */}
      <div>
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-semibold bg-emerald-50 text-emerald-700 border border-emerald-200 mb-2">
          <Coins className="w-3.5 h-3.5" />
          Financial Return On Investment (ROI)
        </div>
        <h2 className="text-3xl font-extrabold text-slate-900 tracking-tight">
          How much money could better decisions affect?
        </h2>
        <p className="text-slate-600 mt-1 text-base">
          Quantifying the operational savings and top-line protection generated by predictive reordering.
        </p>
      </div>

      {/* KPI Cards Row */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">
        <div className="bg-white rounded-2xl p-5 border border-slate-200 shadow-sm">
          <div className="flex items-center justify-between text-slate-500 mb-2">
            <span className="text-xs font-bold uppercase tracking-wider text-slate-400">
              Potential Inventory Savings
            </span>
            <PiggyBank className="w-5 h-5 text-indigo-600" />
          </div>
          <div className="text-3xl font-black text-indigo-600 tracking-tight">
            {formatINR(totalPotentialSavings)}
          </div>
          <div className="text-xs text-slate-500 mt-2 font-medium">
            Avoided penalties + reduced holding costs
          </div>
        </div>

        <div className="bg-white rounded-2xl p-5 border border-slate-200 shadow-sm">
          <div className="flex items-center justify-between text-slate-500 mb-2">
            <span className="text-xs font-bold uppercase tracking-wider text-slate-400">
              Revenue Protected
            </span>
            <ShieldCheck className="w-5 h-5 text-emerald-600" />
          </div>
          <div className="text-3xl font-black text-emerald-600 tracking-tight">
            {formatINR(totalRevenueProtected)}
          </div>
          <div className="text-xs text-slate-500 mt-2 font-medium">
            Turnover preserved by replenishing on time
          </div>
        </div>

        <div className="bg-white rounded-2xl p-5 border border-slate-200 shadow-sm">
          <div className="flex items-center justify-between text-slate-500 mb-2">
            <span className="text-xs font-bold uppercase tracking-wider text-slate-400">
              Reduced Excess Capital
            </span>
            <ArrowDownRight className="w-5 h-5 text-amber-600" />
          </div>
          <div className="text-3xl font-black text-amber-600 tracking-tight">
            {formatINR(totalExcessFreed)}
          </div>
          <div className="text-xs text-slate-500 mt-2 font-medium">
            Dead inventory capital unlocked
          </div>
        </div>

        <div className="bg-gradient-to-br from-indigo-900 to-slate-900 text-white rounded-2xl p-5 shadow-md">
          <div className="text-xs font-bold uppercase tracking-wider text-indigo-300 mb-2">
            Estimated Business Impact
          </div>
          <div className="text-3xl font-black text-emerald-400 tracking-tight">
            {formatINR(estimatedBusinessImpact)}
          </div>
          <div className="text-xs text-indigo-200 mt-2 font-medium">
            Total net annualized value creation
          </div>
        </div>
      </div>

      {/* Mandatory Disclaimer */}
      <div className="bg-amber-50 border border-amber-200/80 rounded-xl p-4 flex items-start gap-3 text-xs text-amber-900">
        <AlertCircle className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
        <div>
          <strong>Managerial Disclaimer:</strong> These are model-based estimates derived from current
          sales run-rates, catalog margins, and stated cost parameters. They represent potential
          improvements over uncalibrated purchasing rather than contractual or guaranteed returns.
        </div>
      </div>

      {/* Expandable Section: How Was This Calculated? */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
        <button
          onClick={() => setShowFormula(!showFormula)}
          className="w-full px-6 py-4 flex items-center justify-between text-left font-bold text-slate-900 hover:bg-slate-50 transition-colors"
        >
          <span className="text-base flex items-center gap-2">
            How Was This Calculated?
          </span>
          {showFormula ? (
            <ChevronUp className="w-5 h-5 text-slate-500" />
          ) : (
            <ChevronDown className="w-5 h-5 text-slate-500" />
          )}
        </button>

        {showFormula && (
          <div className="px-6 pb-6 pt-2 border-t border-slate-100 text-sm text-slate-600 space-y-4">
            <div>
              <h4 className="font-bold text-slate-900 mb-1">1. Revenue Protected Formula:</h4>
              <p className="bg-slate-50 p-3 rounded-xl font-mono text-xs text-slate-800 border border-slate-200">
                Revenue Protected = Units Stockout Prevented × Selling Price (₹)
              </p>
              <p className="text-xs text-slate-500 mt-1">
                Where Units Stockout Prevented represents demand exceeding current inventory that is
                satisfied by timely reordering.
              </p>
            </div>

            <div>
              <h4 className="font-bold text-slate-900 mb-1">2. Avoided Stockout Cost:</h4>
              <p className="bg-slate-50 p-3 rounded-xl font-mono text-xs text-slate-800 border border-slate-200">
                Stockout Penalty Avoided = Units Prevented × (Selling Price - Product Cost) × 1.25 Multiplier
              </p>
              <p className="text-xs text-slate-500 mt-1">
                Incorporates both lost immediate gross profit margin plus an estimated 25% churn penalty
                for buyer disappointment.
              </p>
            </div>

            <div>
              <h4 className="font-bold text-slate-900 mb-1">3. Excess Inventory Carrying Reduction:</h4>
              <p className="bg-slate-50 p-3 rounded-xl font-mono text-xs text-slate-800 border border-slate-200">
                Excess Capital Freed = max(0, Current Stock - Reorder Point) × Product Cost
                <br />
                Weekly Holding Savings = Excess Capital Freed × (18% Annual Holding Rate / 52 weeks)
              </p>
              <p className="text-xs text-slate-500 mt-1">
                Eliminating over-purchases directly preserves liquid cash flow.
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
